# Generated by Django 4.2.29 on 2026-03-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late Arrival'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Approved Leave')], default='PRESENT', max_length=20)),
                ('location', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote / Work From Home'), ('FIELD', 'Field / On-Site')], max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'), models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
